spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring
    username: mateus
    password: gringo
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  flyway:
    enabled: false
    create-schemas: false
server:
  port: 8082